<Project>
  <PropertyGroup>
    <CompanionVersion>$([System.IO.File]::ReadAllText('$(MSBuildThisFileDirectory)..\VERSION').Trim())</CompanionVersion>
    <CompanionBuildNumber>2</CompanionBuildNumber>
    <Version>$(CompanionVersion)</Version>
    <AssemblyVersion>$(CompanionVersion).0</AssemblyVersion>
    <FileVersion>$(CompanionVersion).$(CompanionBuildNumber)</FileVersion>
    <InformationalVersion Condition="'$(SourceRevisionId)' == ''">$(CompanionVersion)</InformationalVersion>
    <InformationalVersion Condition="'$(SourceRevisionId)' != ''">$(CompanionVersion)+$(SourceRevisionId)</InformationalVersion>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
  </PropertyGroup>
</Project>
